// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package pusher.actions;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.pusher.rest.Pusher;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Send a Notify event to all Listen widgets, that are subscribed to the same object and action name.
 * 
 * Please note that this java action is execute asynchronous and will not wait till the pusher services has stared and communicated. Execeptions will not be thrown from the action but will registed in the console log.
 */
public class Notify extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String AppID;
	private java.lang.String Key;
	private java.lang.String Secret;
	private java.lang.String Cluster;
	private IMendixObject NotifyObject;
	private java.lang.String ActionName;

	public Notify(IContext context, java.lang.String AppID, java.lang.String Key, java.lang.String Secret, java.lang.String Cluster, IMendixObject NotifyObject, java.lang.String ActionName)
	{
		super(context);
		this.AppID = AppID;
		this.Key = Key;
		this.Secret = Secret;
		this.Cluster = Cluster;
		this.NotifyObject = NotifyObject;
		this.ActionName = ActionName;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (this.AppID == null || this.AppID.isEmpty()) {
			throw new Exception("AppID parameter should not be empty");
		}
		if (this.Key == null || this.Key.isEmpty()) {
			throw new Exception("Key parameter should not be empty");
		}
		if (this.Secret == null || this.Secret.isEmpty()) {
			throw new Exception("Secret parameter should not be empty");
		}
		if (this.Cluster == null || this.Cluster.isEmpty()) {
			throw new Exception("Cluster parameter should not be empty");
		}
		if (!this.Cluster.matches("eu|mt1|us2|ap1|ap2")){
			throw new Exception("Cluster parameter should a value from the list: eu, mt1, us2, ap1, ap2");
		}
		if (this.NotifyObject == null) {
			throw new Exception("NotifyObject parameter should not be empty");
		}
		if (this.ActionName == null || this.ActionName.isEmpty()) {
			throw new Exception("ActionName parameter should not be empty");
		}

		this.doNotify();

		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Notify";
	}

	// BEGIN EXTRA CODE
	private void doNotify() {
		Pusher pusher = new Pusher(this.AppID, this.Key, this.Secret);
		pusher.setCluster(this.Cluster);
		pusher.setEncrypted(true);

		String guid = Long.toString(this.NotifyObject.getId().toLong());
		String entity = this.NotifyObject.getId().getObjectType();
		String sender = "Application"; 
		if (this.context().getCurrentUserObject() != null) {
			sender = this.context().getCurrentUserObject().getValue(getContext(), "Name");
		}
	
		Map<String, String> payload = new HashMap<String, String>();
		payload.put("guid", guid);		
		payload.put("entity", entity);
		payload.put("sender", sender);
		payload.put("actionName", this.ActionName);

		if (NotifyObject.hasChangedDateAttribute()) {
			Date changeDate = (java.util.Date) this.NotifyObject.getValue(getContext(), "changedDate");
			String time = Long.toString(changeDate.getTime());
			payload.put("changedDate", time);
		}
		
		String channel = "private-" + entity + "." + guid;
		pusher.trigger(channel, this.ActionName, payload);

		ILogNode logger = Core.getLogger("Pusher");
		logger.debug("Send message to channel : " + channel + " action " + this.ActionName);
	}
	// END EXTRA CODE
}
